global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "ragtune-api"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["ragtune-service.ragtune-prod.svc.cluster.local:80"]

  - job_name: "kubernetes-pods"
    kubernetes_sd_configs:
      - role: pod
